version: '3.8'

services:
  cripto-engine:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - NEWS_API_KEY=${NEWS_API_KEY}
      - APITUBE_API_KEY=${APITUBE_API_KEY}
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
    restart: unless-stopped